site_name: nanopie Documentation
nav:
  - Home: index.md
  - Services: services.md
  - Data Model: data-model.md
  - Transport: transport.md
  - Authentication: authentication.md
  - Logging: logging.md
  - Tracing: tracing.md
  - Serialization: serialization.md
  - About: about.md
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences